#!/bin/bash

for file in *; do
    # Check if the file is not a hidden file
    if [[ ! $file == .* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        
        # Display the formatted output
        echo "- $name_after_dash"
    fi
done
