#!/usr/bin/env bash
# To change the ip adresses of localhost and facebook on my pc

cp /etc/hosts ~/hosts.new
sed -i "s/^127\.0\.0\.1\tlocalhost/127.0.0.2 localhost/" ~/hosts.new
sed -i "$ a\8.8.8.8\tfacebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
